# Generated by Django 3.0.5 on 2020-04-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_auto_20200409_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Antwoord',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='Onderdeel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
