# Generated by Django 3.0.5 on 2020-04-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_auto_20200428_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
