# Generated by Django 3.0.5 on 2020-04-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0004_post_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Thumb',
        ),
    ]
